export const lexicalTheme = {
  paragraph: "text-base leading-relaxed text-foreground",
  heading: {
    h1: "font-display text-3xl sm:text-4xl tracking-tight",
    h2: "font-display text-2xl sm:text-3xl tracking-tight",
    h3: "font-display text-xl sm:text-2xl tracking-tight",
  },
  quote: "border-l-4 border-foreground/10 pl-4 italic text-muted-foreground",
  code: "font-mono text-sm bg-slate-900 text-slate-100 p-4 rounded-xl overflow-x-auto",
  list: {
    ul: "list-disc pl-6",
    ol: "list-decimal pl-6",
    listitem: "my-1",
    listitemChecked: "line-through text-muted-foreground",
    listitemUnchecked: "text-foreground",
    nested: {
      listitem: "list-none",
    },
  },
  link: "text-sky-700 underline underline-offset-4",
  text: {
    bold: "font-semibold",
    italic: "italic",
    underline: "underline",
    strikethrough: "line-through",
    code: "font-mono text-sm bg-black/5 px-1.5 py-0.5 rounded",
  },
  table: "w-full border-collapse text-sm my-3",
  tableCell: "border border-black/10 px-2 py-1 align-top relative",
  tableCellHeader: "bg-black/5 font-semibold",
  tableCellSelected: "bg-sky-100",
  tableCellPrimarySelected: "bg-sky-200",
  tableRow: "align-top",
  tableRowStriped: "odd:bg-black/[0.02]",
  tableScrollableWrapper: "overflow-x-auto -mx-4 px-4",
  tableSelection: "bg-sky-500/30",
  tableSelected: "outline outline-2 outline-sky-500",
  tableCellResizer: "absolute right-0 top-0 bottom-0 w-1 cursor-col-resize bg-transparent hover:bg-sky-500",
  hr: "my-6 border-black/10",
  hrSelected: "outline outline-2 outline-sky-300",
  codeHighlight: {
    atrule: "text-purple-300",
    attr: "text-sky-300",
    boolean: "text-amber-300",
    builtin: "text-emerald-300",
    cdata: "text-slate-400",
    char: "text-emerald-200",
    class: "text-teal-300",
    comment: "text-slate-400",
    constant: "text-amber-200",
    deleted: "text-rose-300",
    doctype: "text-slate-400",
    entity: "text-amber-200",
    function: "text-sky-300",
    important: "text-amber-300",
    inserted: "text-emerald-300",
    keyword: "text-purple-300",
    namespace: "text-emerald-300",
    number: "text-amber-200",
    operator: "text-slate-200",
    property: "text-sky-300",
    punctuation: "text-slate-200",
    regex: "text-rose-200",
    selector: "text-emerald-300",
    string: "text-emerald-200",
    symbol: "text-amber-200",
    tag: "text-sky-300",
    url: "text-sky-300",
    variable: "text-amber-200",
  },
};
