-- AlterTable
ALTER TABLE "Category" ADD COLUMN "showOnHome" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "homeItemCount" INTEGER NOT NULL DEFAULT 3;

-- AlterTable
ALTER TABLE "Board" ADD COLUMN "showOnHome" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "homeItemCount" INTEGER NOT NULL DEFAULT 5;
